// import { CustomHead } from "/src/components";

export default function Home() {
  return (
    <div>
      {/*<Head>*/}
      {/*    <title>Create Next App</title>*/}
      {/*    <meta name="description" content="Generated by create next app"/>*/}
      {/*    <meta name="viewport" content="width=device-width, initial-scale=1"/>*/}
      {/*    <link rel="icon" href="/favicon.ico"/>*/}
      {/*</Head>*/}

      <div>
        <p>TESTING</p>
      </div>
    </div>
  );
}
